import { Table, clean, findHeaderRow, readDateTime } from "./table";

export type ZohoCandidate = { createdAt: string; date: string; utmSource: string; positions: string[] };
export type ZohoReport = {
  org: string | null;           // from "Generated by …" (reports only; full module exports don't have it)
  title: string | null;
  positionColumns: string[];
  candidates: ZohoCandidate[];
  usedLeadSource: number;       // candidates whose blank UTM Source was filled from Lead Source
  columnCount: number;
};
export type ZohoOptions = {
  /** Columns that say what someone applied for. Yes/No columns use the column name as the position;
   *  text or multi-select columns ("Trooper;Commercial Vehicle Officer") use each value. */
  positionFields?: string[];
};

const NOT_POSITIONS = new Set([
  "created time", "modified time", "utm source", "utm medium", "utm campaign", "utm term", "utm content",
  "record id", "id", "email", "phone", "mobile", "first name", "last name", "full name", "candidate name", "name",
  "lead source", "owner", "candidate owner", "city", "state", "zip code",
]);
const TRUE = new Set(["true", "yes", "1", "y", "checked"]);
const FALSE = new Set(["false", "no", "0", "n", "unchecked", ""]);
const BOOLISH = new Set([...TRUE, ...FALSE]);
const GROUP_LABEL = /^(.*?)\s*\(\s*\d+\s*\)\s*$/;
const BLANK_SOURCE = /^(null|-|none|\(none\)|\(blank\))$/i;
/** Auto-detecting Yes/No position columns only makes sense on a short custom report; a full module export has dozens of unrelated checkboxes. */
const AUTO_DETECT_MAX_COLUMNS = 15;

const headerTest = (c: string[]) => c.includes("created time") && c.includes("utm source");
export const looksLikeZoho = (t: Table) => findHeaderRow(t, headerTest) >= 0;

export function parseZoho(t: Table, opts: ZohoOptions = {}): ZohoReport {
  const hi = findHeaderRow(t, headerTest);
  if (hi < 0) throw new Error("No 'Created Time' + 'UTM Source' header row found.");
  const header = (t[hi] || []).map(c => clean(c));
  const lower = header.map(h => h.toLowerCase());
  const createdIdx = lower.indexOf("created time");
  const utmIdx = lower.lastIndexOf("utm source");
  const leadIdx = lower.indexOf("lead source");
  const isGroupColumnOnly = utmIdx === 0 && lower.indexOf("utm source") === utmIdx && createdIdx > 0;
  const columnCount = header.filter(Boolean).length;

  let org: string | null = null, title: string | null = null;
  for (let i = 0; i < hi; i++) {
    const s = (t[i] || []).map(clean).join(" ").trim();
    const m = s.match(/Generated by (.+?) on /i);
    if (m) org = m[1].trim();
    else if (s && !title && !/record count/i.test(s)) title = s;
  }

  const dataRows = t.slice(hi + 1).filter(r => r && readDateTime(r[createdIdx] ?? null));

  // Which columns hold positions
  let posCols: { h: string; i: number; bool: boolean }[];
  if (opts.positionFields?.length) {
    posCols = opts.positionFields
      .map(f => ({ h: f, i: lower.indexOf(f.trim().toLowerCase()) }))
      .filter(p => p.i >= 0)
      .map(p => ({ h: header[p.i], i: p.i, bool: dataRows.every(r => BOOLISH.has(clean(r[p.i] ?? null).toLowerCase())) }));
  } else if (columnCount <= AUTO_DETECT_MAX_COLUMNS) {
    posCols = header
      .map((h, i) => ({ h, i, bool: true }))
      .filter(({ h, i }) => h && i !== createdIdx && i !== utmIdx && !NOT_POSITIONS.has(h.toLowerCase()))
      .filter(({ i }) => dataRows.length > 0 && dataRows.every(r => BOOLISH.has(clean(r[i] ?? null).toLowerCase())));
  } else posCols = [];

  let carried = "", usedLeadSource = 0;
  const candidates: ZohoCandidate[] = dataRows.map(r => {
    const dt = readDateTime(r[createdIdx] ?? null)!;
    let utm = clean(r[utmIdx] ?? null);
    if (isGroupColumnOnly) {
      const g = utm.match(GROUP_LABEL);
      if (g) carried = g[1].trim(); else if (utm) carried = utm;
      utm = carried;
    }
    if (BLANK_SOURCE.test(utm)) utm = "";
    if (!utm && leadIdx >= 0) {
      const lead = clean(r[leadIdx] ?? null);
      if (lead && !BLANK_SOURCE.test(lead)) { utm = lead; usedLeadSource++; }
    }
    const positions = new Set<string>();
    for (const p of posCols) {
      const v = clean(r[p.i] ?? null);
      if (!v) continue;
      if (p.bool) { if (TRUE.has(v.toLowerCase())) positions.add(p.h); }
      else for (const part of v.split(/;|\|/).map(s => s.trim()).filter(Boolean)) positions.add(part);
    }
    return { createdAt: dt.ts, date: dt.date, utmSource: utm, positions: [...positions] };
  });

  return { org, title, positionColumns: posCols.map(p => p.h), candidates, usedLeadSource, columnCount };
}
