import { Table, clean, findHeaderRow, readDateTime } from "./table";

export type ZohoCandidate = { createdAt: string; date: string; utmSource: string; positions: string[] };
export type ZohoReport = { org: string | null; title: string | null; positionColumns: string[]; candidates: ZohoCandidate[] };

const NOT_POSITIONS = new Set([
  "created time", "modified time", "utm source", "utm medium", "utm campaign", "utm term", "utm content",
  "record id", "id", "email", "phone", "mobile", "first name", "last name", "full name", "candidate name", "name",
  "lead source", "owner", "candidate owner", "city", "state", "zip code",
]);
const TRUE = new Set(["true", "yes", "1", "y", "checked"]);
const BOOLISH = new Set(["true", "false", "yes", "no", "1", "0", "y", "n", "checked", "unchecked", ""]);
const GROUP_LABEL = /^(.*?)\s*\(\s*\d+\s*\)\s*$/;

export function looksLikeZoho(t: Table): boolean {
  return findHeaderRow(t, c => c.includes("created time") && c.includes("utm source")) >= 0;
}

export function parseZoho(t: Table): ZohoReport {
  const hi = findHeaderRow(t, c => c.includes("created time") && c.includes("utm source"));
  if (hi < 0) throw new Error("No 'Created Time' + 'UTM Source' header row found.");
  const header = (t[hi] || []).map(c => clean(c));
  const lower = header.map(h => h.toLowerCase());
  const createdIdx = lower.indexOf("created time");
  const utmIdx = lower.lastIndexOf("utm source");
  const isGroupColumnOnly = utmIdx === 0 && lower.indexOf("utm source") === utmIdx && createdIdx > 0;

  let org: string | null = null, title: string | null = null;
  for (let i = 0; i < hi; i++) {
    const s = (t[i] || []).map(clean).join(" ").trim();
    const m = s.match(/Generated by (.+?) on /i);
    if (m) org = m[1].trim();
    else if (s && !title && !/record count/i.test(s)) title = s;
  }

  const dataRows = t.slice(hi + 1).filter(r => r && readDateTime(r[createdIdx] ?? null));
  const positionColumns = header
    .map((h, i) => ({ h, i }))
    .filter(({ h, i }) => h && i !== createdIdx && i !== utmIdx && !NOT_POSITIONS.has(h.toLowerCase()))
    .filter(({ i }) => dataRows.length > 0 && dataRows.every(r => BOOLISH.has(clean(r[i] ?? null).toLowerCase())));

  let carried = "";
  const candidates: ZohoCandidate[] = dataRows.map(r => {
    const dt = readDateTime(r[createdIdx] ?? null)!;
    let utm = clean(r[utmIdx] ?? null);
    if (isGroupColumnOnly) {
      const g = utm.match(GROUP_LABEL);
      if (g) carried = g[1].trim(); else if (utm) carried = utm;
      utm = carried;
    }
    if (/^(null|-|none|\(none\))$/i.test(utm)) utm = "";
    const positions = positionColumns.filter(({ i }) => TRUE.has(clean(r[i] ?? null).toLowerCase())).map(({ h }) => h);
    return { createdAt: dt.ts, date: dt.date, utmSource: utm, positions };
  });

  return { org, title, positionColumns: positionColumns.map(p => p.h), candidates };
}
