"use client";

import { useActionState, useRef, useState } from "react";
import { saveSpend, runImportNow, uploadReports, saveClient, assignSpend, backfillApiSpend, type ActionState } from "@/app/actions";

export function SpendForm({ clientId, week, channel, amount, missing, label }:
  { clientId: number; week: string; channel: string; amount: number | null; missing: boolean; label: string }) {
  const [state, action, pending] = useActionState(saveSpend, {} as ActionState);
  const formRef = useRef<HTMLFormElement>(null);
  const id = `spend-${clientId}-${week}-${channel}`;
  return (
    <form ref={formRef} action={action} style={{ display: "inline-flex", alignItems: "center", gap: 8 }}>
      <input type="hidden" name="clientId" value={clientId} />
      <input type="hidden" name="week" value={week} />
      <input type="hidden" name="channel" value={channel} />
      <label className={`spendbox${missing ? " missing" : ""}`} htmlFor={id}>
        <span>$</span>
        <input id={id} name="amount" inputMode="decimal" autoComplete="off" placeholder="0.00" aria-label={label}
          defaultValue={amount == null ? "" : amount.toFixed(2)} disabled={pending}
          onBlur={e => { if (e.currentTarget.value !== (amount == null ? "" : amount.toFixed(2))) formRef.current?.requestSubmit(); }} />
      </label>
      {pending ? <span className="tag">Saving…</span> : state.error ? <span className="tag" style={{ color: "var(--bad)" }}>{state.error}</span> : state.ok ? <span className="tag" style={{ color: "var(--good)" }}>{state.ok}</span> : null}
    </form>
  );
}

function Result({ state }: { state: ActionState }) {
  if (state.error) return <pre className="msg bad log">{state.error}</pre>;
  if (state.ok) return <pre className="msg good log">{state.ok}</pre>;
  return null;
}

export function RunImportButton() {
  const [state, action, pending] = useActionState(runImportNow, {} as ActionState);
  return (
    <form action={action} style={{ display: "grid", gap: 10 }}>
      <div><button className="btn primary" disabled={pending}>{pending ? "Importing…" : "Run import now"}</button></div>
      <Result state={state} />
    </form>
  );
}

// Vercel rejects requests over 4.5 MB before they reach the app, so check in the browser first.
const MAX_UPLOAD = 4.2 * 1024 * 1024;

export function UploadForm({ clients }: { clients: { id: number; name: string }[] }) {
  const [state, action, pending] = useActionState(uploadReports, {} as ActionState);
  const [tooBig, setTooBig] = useState<string | null>(null);
  return (
    <form action={action} style={{ display: "grid", gap: 10 }}
      onSubmit={e => { if (tooBig) e.preventDefault(); }}>
      <input type="file" name="files" multiple accept=".csv,.tsv,.xlsx" aria-label="Report files"
        onChange={e => {
          const total = [...(e.currentTarget.files ?? [])].reduce((a, f) => a + f.size, 0);
          setTooBig(total > MAX_UPLOAD
            ? `These files add up to ${(total / 1024 / 1024).toFixed(1)} MB; the limit per upload is 4 MB. Upload them in smaller batches, or export only the columns the dashboard needs (Created Time, UTM Source, Lead Source and the position fields), which makes even years of history small.`
            : null);
        }} />
      <label className="field" htmlFor="upload-client">Client for Zoho files that don&apos;t name their account
        <select id="upload-client" name="clientId" defaultValue="">
          <option value="">Match automatically (Zoho reports say “Generated by …”)</option>
          {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>
      </label>
      {tooBig && <pre className="msg bad log">{tooBig}</pre>}
      <div><button className="btn" disabled={pending || !!tooBig}>{pending ? "Importing…" : "Import files"}</button></div>
      <Result state={state} />
    </form>
  );
}

export type ClientFormValues = {
  id?: number; name: string; zoho_org: string | null; channels: string[]; meta_match: string[]; google_match: string[];
  default_position: string | null; source_map: Record<string, string>; active: boolean; position_fields: string[];
};

export function ClientForm({ c }: { c?: ClientFormValues }) {
  const [state, action, pending] = useActionState(saveClient, {} as ActionState);
  const v = c ?? { name: "", zoho_org: "", channels: [], meta_match: [], google_match: [], default_position: "", source_map: {}, active: true, position_fields: [] };
  const pre = `c${c?.id ?? "new"}`;
  return (
    <form action={action} style={{ display: "grid", gap: 12 }}>
      {c?.id && <input type="hidden" name="id" value={c.id} />}
      <div className="form-grid">
        <label className="field" htmlFor={`${pre}-name`}>Client name<input id={`${pre}-name`} type="text" name="name" defaultValue={v.name} required /></label>
        <label className="field" htmlFor={`${pre}-zoho`}>Zoho account name (as in “Generated by …”)<input id={`${pre}-zoho`} type="text" name="zoho_org" defaultValue={v.zoho_org ?? ""} /></label>
        <label className="field" htmlFor={`${pre}-pos`}>Default position (if Zoho has no position fields)<input id={`${pre}-pos`} type="text" name="default_position" defaultValue={v.default_position ?? ""} placeholder="e.g. Trooper" /></label>
      </div>
      <div className="field">Paid channels
        <div className="checks">
          {["Meta", "Google", "Indeed"].map(ch => (
            <label key={ch}><input type="checkbox" name={`ch_${ch}`} defaultChecked={v.channels.includes(ch)} /> {ch}</label>
          ))}
          <label><input type="checkbox" name="active" defaultChecked={v.active} /> Active</label>
        </div>
      </div>
      <div className="form-grid">
        <label className="field" htmlFor={`${pre}-meta`}>Meta campaigns containing (one per line)<textarea id={`${pre}-meta`} name="meta_match" defaultValue={v.meta_match.join("\n")} /></label>
        <label className="field" htmlFor={`${pre}-google`}>Google Ads account names or IDs (one per line)<textarea id={`${pre}-google`} name="google_match" defaultValue={v.google_match.join("\n")} /></label>
        <label className="field" htmlFor={`${pre}-posf`}>Zoho position fields (one per line)<textarea id={`${pre}-posf`} name="position_fields" defaultValue={v.position_fields.join("\n")} placeholder={"Trooper\nCommercial Vehicle Officer"} /></label>
        <label className="field" htmlFor={`${pre}-map`}>UTM Source overrides (source = channel)<textarea id={`${pre}-map`} name="source_map" defaultValue={Object.entries(v.source_map).map(([k, x]) => `${k} = ${x}`).join("\n")} placeholder="chatgpt.com = Organic" /></label>
      </div>
      <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
        <button className="btn primary" disabled={pending}>{pending ? "Saving…" : c?.id ? "Save client" : "Add client"}</button>
        {state.ok && <span className="tag" style={{ color: "var(--good)" }}>{state.ok}</span>}
        {state.error && <span className="tag" style={{ color: "var(--bad)" }}>{state.error}</span>}
      </div>
    </form>
  );
}

export function AssignForm({ platform, k, clients }: { platform: string; k: string; clients: { id: number; name: string }[] }) {
  const [state, action, pending] = useActionState(assignSpend, {} as ActionState);
  const id = `as-${platform}-${k}`.replace(/[^\w-]/g, "_");
  return (
    <form action={action} style={{ display: "inline-flex", gap: 6, alignItems: "center" }}>
      <input type="hidden" name="platform" value={platform} />
      <input type="hidden" name="key" value={k} />
      <select id={id} name="clientId" aria-label={`Client for ${k}`} defaultValue="">
        <option value="" disabled>Assign to…</option>
        {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
      </select>
      <button className="btn small" disabled={pending}>Assign</button>
      {state.ok && <span className="tag" style={{ color: "var(--good)" }}>Done</span>}
      {state.error && <span className="tag" style={{ color: "var(--bad)" }}>{state.error}</span>}
    </form>
  );
}

export function BackfillForm({ defaultSince }: { defaultSince: string }) {
  const [state, action, pending] = useActionState(backfillApiSpend, {} as ActionState);
  return (
    <form action={action} style={{ display: "grid", gap: 10 }}>
      <label className="field" htmlFor="backfill-since">Pull spend starting from
        <input id="backfill-since" type="date" name="since" defaultValue={defaultSince} style={{ font: "14px var(--body)", color: "var(--ink)", background: "var(--surface)", border: "1px solid var(--line)", borderRadius: 6, padding: "7px 10px", maxWidth: 220 }} />
      </label>
      <div><button className="btn" disabled={pending}>{pending ? "Pulling history…" : "Backfill API spend"}</button></div>
      <Result state={state} />
    </form>
  );
}
