-- CPC Dashboard schema. Safe to run more than once.

CREATE TABLE IF NOT EXISTS clients (
  id               SERIAL PRIMARY KEY,
  slug             TEXT UNIQUE NOT NULL,
  name             TEXT NOT NULL,
  zoho_org         TEXT,                          -- text after "Generated by" in the Zoho export
  channels         TEXT[] NOT NULL DEFAULT '{}',  -- paid channels this client runs: Meta, Google, Indeed
  meta_match       TEXT[] NOT NULL DEFAULT '{}',  -- Meta campaign names containing any of these belong to this client
  google_match     TEXT[] NOT NULL DEFAULT '{}',  -- Google Ads account names or customer IDs
  default_position TEXT,                          -- used when the Zoho report has no position columns (e.g. Trooper)
  source_map       JSONB NOT NULL DEFAULT '{}',   -- per-client UTM Source -> channel overrides
  position_fields  TEXT[] NOT NULL DEFAULT '{}',  -- Zoho columns that say which position(s) someone wants
  active           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Added after first release; safe to re-run.
ALTER TABLE clients ADD COLUMN IF NOT EXISTS position_fields TEXT[] NOT NULL DEFAULT '{}';

-- One row per candidate from the weekly Zoho report. Re-importing a client's week replaces that week.
CREATE TABLE IF NOT EXISTS candidates (
  id          BIGSERIAL PRIMARY KEY,
  client_id   INT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  week_start  DATE NOT NULL,           -- Sunday
  created_at  TIMESTAMP NOT NULL,      -- as shown in Zoho (client's local time)
  utm_source  TEXT NOT NULL,
  channel     TEXT NOT NULL,           -- Meta, Google, Indeed, Organic, Untracked, Other
  positions   TEXT[] NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS candidates_client_week ON candidates (client_id, week_start);

-- Daily spend as reported by each platform, before it is matched to a client.
CREATE TABLE IF NOT EXISTS spend_raw (
  platform    TEXT NOT NULL,           -- Meta | Google
  key         TEXT NOT NULL,           -- Meta: campaign name. Google: account name
  account_id  TEXT,                    -- Meta ad account / Google customer ID when known
  day         DATE NOT NULL,
  amount      NUMERIC(12,2) NOT NULL,
  source      TEXT NOT NULL,           -- api | email | upload
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (platform, key, day)
);
CREATE INDEX IF NOT EXISTS spend_raw_day ON spend_raw (day);

-- Spend typed in by a person (Indeed, or a correction). Wins over imported spend for that channel and week.
CREATE TABLE IF NOT EXISTS spend_manual (
  client_id   INT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  week_start  DATE NOT NULL,
  channel     TEXT NOT NULL,
  amount      NUMERIC(12,2) NOT NULL,
  updated_by  TEXT NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (client_id, week_start, channel)
);

CREATE TABLE IF NOT EXISTS import_log (
  id          BIGSERIAL PRIMARY KEY,
  ran_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  trigger     TEXT NOT NULL,           -- cron | manual | upload
  source      TEXT NOT NULL,           -- outlook | meta-api | google-api | upload
  status      TEXT NOT NULL,           -- ok | skipped | error
  message     TEXT NOT NULL
);

-- Outlook attachments already imported, so a rerun does not double count.
CREATE TABLE IF NOT EXISTS imported_files (
  file_key    TEXT PRIMARY KEY,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
